**Mashalov Rasulbek**,
OSTC2U,
Machine Learning,
HomeWork 1,
12th February, 2026.

**EXERCISE 1**

In [12]:
#Exercise 1
class Class:
    # Task 1: Replace 'a' with 'X'
    def replace_chars(self, text):
        # Built-in .replace() method is used
        new_text = text.replace('a', 'X')
        return new_text

    # Task 2: Return the fractional part of a number
    def get_fractional_part(self, number):
        # To do this, I subtract the integer part from the whole number
        fractional_part = number - int(number)
        return fractional_part

In [13]:
#Task 1 proof
proof1 = Class()
input = "banana"
output = proof1.replace_chars(input)
print(f"Output: {output}")

Output: bXnXnX


In [14]:
proof2 = Class()
input = 12.3434
output = proof2.get_fractional_part(input)
print(f"Output: {output}")

Output: 0.3434000000000008


**EXERCISE 2**

In [19]:
#Exercise 2
#class imporinting and matrix defining
import numpy as np

A = np.array([
    [5, 6, 8],
    [2, 3, 2]
])

B = np.array([
    [1, 3, 1],
    [2, 3, 3]
])

In [20]:
#Dot product
#To flip (transpose) B to make the inner dimensions match for multiplication, I use .T
dot_product = np.dot(A, B.T)
print("1. Dot product:\n", dot_product)

1. Dot product:
 [[31 52]
 [13 19]]


In [21]:
#Elementwise product
elementwise = A * B
print("\n2. Elementwise product:\n", elementwise)


2. Elementwise product:
 [[ 5 18  8]
 [ 4  9  6]]


In [22]:
#Sum
matrix_sum = A + B
print("\n3. Sum:\n", matrix_sum)


3. Sum:
 [[6 9 9]
 [4 6 5]]


In [23]:
#Sum of the A matrix elements
sum_of_A = np.sum(A)
print("\n4. Sum of A elements:", sum_of_A)


4. Sum of A elements: 26


In [24]:
#The first row of the B matrix
#I slice with [0] to get the first row
row_0_B = B[0]
print("\n5. First row of B:", row_0_B)


5. First row of B: [1 3 1]


In [25]:
#The second column of the B matrix
col_1_B = B[:, 1]
print("\n6. Second column of B:", col_1_B)


6. Second column of B: [3 3]


In [26]:
#Create a C matrix from A without A's first column
C = A[:, 1:]
print("\n7. C matrix (A without first column):\n", C)


7. C matrix (A without first column):
 [[6 8]
 [3 2]]


**Exercise 3**

In [7]:
#Exercise 3
#Morce code defining
def decode_morse_message(morse_string):
    morse_code_dict = {
        '.-': 'A',   '-...': 'B',   '-.-.': 'C',
        '-..': 'D',  '.': 'E',      '..-.': 'F',
        '--.': 'G',  '....': 'H',   '..': 'I',
        '.---': 'J', '-.-': 'K',    '.-..': 'L',
        '--': 'M',   '-.': 'N',     '---': 'O',
        '.--.': 'P', '--.-': 'Q',   '.-.': 'R',
        '...': 'S',  '-': 'T',      '..-': 'U',
        '...-': 'V', '.--': 'W',    '-..-': 'X',
        '-.--': 'Y', '--..': 'Z',
        '/': ' '  # / is to represent a space between words
    }
    
    #Splitting the message into a list of codes
    #The .split(' ') is to seprate the messages when there is a space
    code_list = morse_string.split(' ')
    
    #Creating an empty string to hold the result
    decoded_text = ""
    
    #Loopping through every code in our list
    for code in code_list:
        if code in morse_code_dict:
            decoded_text += morse_code_dict[code]
    
    return decoded_text


#Result
input = ".-- . .-.. -.-. --- -- . / .. -. / - .... . / -- .-.. / -.-. --- ..- .-. ... ."

output = decode_morse_message(input)

print("Output:", output)

Output: WELCOME IN THE ML COURSE


In [8]:
#practice
input = "- .... .- -. -.- / -.-- --- ..- -.-.--"
output = decode_morse_message(input)
print(output)

THANK YOU
